### ISSUE TITLE
slushjs library option does not use standalone

### ISSUE THREAD

**Issue by mj3cheun** [maxkfranz/slush-js#6]
When initializing library using slushjs, the standalone option is not passed to browserify, which means requiring the resulting build file does not work as dependencies are not packaged. I had to manually add "standalone: '[PKG NAME]'" in order to make it work.

**Comment by maxkfranz** [comment]
Dependencies should not be packaged in either case.

For a lib with deps, the dev is expected to use webpack or browserify -- or manage global deps.

For an app, there's a separate bundle for the deps (for better caching).

**Comment by mj3cheun** [comment]
Ok, but presumably the packaged js file is intended for use in script tags or something, as anyone using a build tool will simply go through the main index file instead of the build file. For this use case, should all the dependencies be included?

EDIT: Sorry I was not clear, I was testing the build file by simply replacing the main entry point with the bundle.

**Comment by maxkfranz** [comment]
Those people can manage global deps.  Browserify generates a UMD export that should work with globals if you put the `<script>`s in the right order.

**Comment by maxkfranz** [comment]
If you want to support `<script>` tags, then it's important to not have too many dependencies (ideally none).

**Comment by maxkfranz** [comment]
`standalone: true` set in 1.2.1 for lib option

**Comment by mj3cheun** [comment]
Neat thanks.
