### ISSUE TITLE
[FEATURE REQUEST] Perform 1 - 1 transpiling of ES6 to ES5

### ISSUE THREAD

**Issue by mj3cheun** [maxkfranz/slush-js#7]
If you write the library using ES6, it may be required that a 1 - 1 transpiling of ES6 to ES5 be  performed if you wish to publish as some build tools do not automatically do transpiling of dependencies. The alternative option is to set the main entry file in package.json as the browserified bundle in the build folder. See https://github.com/mj3cheun/pathway-commons/tree/master/dist for an example of what the dist folder can look like after compilation.

**Comment by maxkfranz** [comment]
If you use ES6 features that aren't supported by the browsers currently (caniuse.com) or Node, then your `main` has to be the dist file.  The dist file should be unminified and include a sourcemap.
